version: '3.8'

services:
  backend:
    build: ./backend
    container_name: easycrud-backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - easycrud-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: easycrud-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - easycrud-network
    restart: unless-stopped

networks:
  easycrud-network:
    driver: bridge
